apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c7e3a2b25d6235f1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-deployment
  labels:
    purpose: ebs-static
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: ebs-static
      project: roboshop
  template:
    metadata:
      labels:
        purpose: ebs-static
        project: roboshop
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a
      containers:
      - name: ebs-container
        image: nginx
        volumeMounts:
        - name: ebs-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ebs-volume
        persistentVolumeClaim:
          claimName: static-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ebs-service
  labels:
    purpose: ebs-static
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
