apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
  labels:
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardware
                operator: In
                values:
                  - gpu
      containers:
      - name: with-node-affinity
        image: nginx
