---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-xx
  labels:
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
      nodeSelector:
        disktype: ssd